### ISSUE TITLE
area of a non-closed mesh?

### ISSUE THREAD

**Issue by wcornwell** [stla/MeshesTools#1]
I understand that `MeshesTools::meshArea` only works for closed meshes, but I have some non-closed meshes that I would like to calculate (one-sided) areas of.  I *think* it's similar to [this problem and answer](https://stackoverflow.com/questions/26312570/calculate-surface-area-of-a-3d-mesh?rq=1).  

Is this possible with the tools in `MeshesTools`?

**Comment by wcornwell** [comment]
never mind, i think i figured it out

**Comment by stla** [comment]
Are you sure? The mesh must be closed for the *volume*, not for the *area*.

**Comment by stla** [comment]
FYI, this package will not be further developed. It will be replaced with [cgalMeshes](https://github.com/stla/cgalMeshes), which is better.

**Comment by wcornwell** [comment]
@stla thanks!  the problem was self-intersection in the mesh, not the non-closedness.  Thanks for the tip. I'll check out cgalMeshes.

**Comment by stla** [comment]
It's possible to remove the self-intersections with **cgalMeshes**.
